-- MySQL Script generated by MySQL Workbench
-- Wed Dec  3 01:01:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`weathers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`weathers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seasons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rarities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rarities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `multiplier` DECIMAL NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`biomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`biomes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_moderator` TINYINT NULL,
  `is_admin` TINYINT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `is_active` TINYINT NULL,
  `money_amount` DECIMAL NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`professions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `is_active` TINYINT NULL,
  `image` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subclasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subclasses` (
  `professions_parent_id` INT NOT NULL,
  `professions_child_id` INT NOT NULL,
  PRIMARY KEY (`professions_parent_id`, `professions_child_id`),
  INDEX `fk_professions_has_professions_professions2_idx` (`professions_child_id` ASC) VISIBLE,
  INDEX `fk_professions_has_professions_professions1_idx` (`professions_parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_professions_has_professions_professions1`
    FOREIGN KEY (`professions_parent_id`)
    REFERENCES `mydb`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professions_has_professions_professions2`
    FOREIGN KEY (`professions_child_id`)
    REFERENCES `mydb`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_subclasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_subclasses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `professions_id` INT NOT NULL,
  `xp` INT NULL,
  `level` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  INDEX `fk_user_has_professions_professions1_idx` (`professions_id` ASC) VISIBLE,
  INDEX `fk_user_has_professions_user1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_professions_user1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_professions_professions1`
    FOREIGN KEY (`professions_id`)
    REFERENCES `mydb`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`users_professions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_professions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `professions_id` INT NOT NULL COMMENT 'MAX 3: une primaire et 2 scondaires. ',
  `xp` INT NULL,
  `level` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  INDEX `fk_user_has_professions_professions1_idx` (`professions_id` ASC) VISIBLE,
  INDEX `fk_user_has_professions_user1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_professions_user10`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_professions_professions10`
    FOREIGN KEY (`professions_id`)
    REFERENCES `mydb`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`resources_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resource_types_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `is_active` TINYINT NULL,
  `rarities_id` INT NOT NULL,
  `weight` DECIMAL NULL,
  `stack_size` DECIMAL NULL,
  `is_lootable` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resource_resource_types1_idx` (`resource_types_id` ASC) VISIBLE,
  INDEX `fk_resource_rarities1_idx` (`rarities_id` ASC) VISIBLE,
  CONSTRAINT `fk_resource_resource_types1`
    FOREIGN KEY (`resource_types_id`)
    REFERENCES `mydb`.`resources_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_rarities1`
    FOREIGN KEY (`rarities_id`)
    REFERENCES `mydb`.`rarities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`resources_professions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources_professions` (
  `resources_id` INT NOT NULL,
  `professions_id` INT NOT NULL,
  PRIMARY KEY (`resources_id`, `professions_id`),
  INDEX `fk_resource_has_professions_professions1_idx` (`professions_id` ASC) VISIBLE,
  INDEX `fk_resource_has_professions_resource1_idx` (`resources_id` ASC) VISIBLE,
  CONSTRAINT `fk_resource_has_professions_resource1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_has_professions_professions1`
    FOREIGN KEY (`professions_id`)
    REFERENCES `mydb`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`resources_biomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources_biomes` (
  `resources_id` INT NOT NULL,
  `biomes_id` INT NOT NULL,
  `multiplier` DECIMAL NULL,
  PRIMARY KEY (`resources_id`, `biomes_id`),
  INDEX `fk_resource_has_biomes_biomes1_idx` (`biomes_id` ASC) VISIBLE,
  INDEX `fk_resource_has_biomes_resource1_idx` (`resources_id` ASC) VISIBLE,
  CONSTRAINT `fk_resource_has_biomes_resource1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_has_biomes_biomes1`
    FOREIGN KEY (`biomes_id`)
    REFERENCES `mydb`.`biomes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`resources_weathers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources_weathers` (
  `resources_id` INT NOT NULL,
  `weathers_id` INT NOT NULL,
  `multiplier` DECIMAL NULL,
  `resources_weatherscol` VARCHAR(45) NULL,
  PRIMARY KEY (`resources_id`, `weathers_id`),
  INDEX `fk_resource_has_weathers_weathers1_idx` (`weathers_id` ASC) VISIBLE,
  INDEX `fk_resource_has_weathers_resource1_idx` (`resources_id` ASC) VISIBLE,
  CONSTRAINT `fk_resource_has_weathers_resource1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_has_weathers_weathers1`
    FOREIGN KEY (`weathers_id`)
    REFERENCES `mydb`.`weathers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`resources_seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources_seasons` (
  `resources_id` INT NOT NULL,
  `seasons_id` INT NOT NULL,
  `multiplier` DECIMAL NULL,
  PRIMARY KEY (`resources_id`, `seasons_id`),
  INDEX `fk_resources_has_seasons_seasons1_idx` (`seasons_id` ASC) VISIBLE,
  INDEX `fk_resources_has_seasons_resources1_idx` (`resources_id` ASC) VISIBLE,
  CONSTRAINT `fk_resources_has_seasons_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resources_has_seasons_seasons1`
    FOREIGN KEY (`seasons_id`)
    REFERENCES `mydb`.`seasons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventory_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_inventory_resources1_idx` (`resources_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resources_id` INT NOT NULL,
  `professions_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `is_active` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recipes_resources1_idx` (`resources_id` ASC) VISIBLE,
  INDEX `fk_recipes_professions1_idx` (`professions_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipes_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_professions1`
    FOREIGN KEY (`professions_id`)
    REFERENCES `mydb`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`recipes_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipes_resources` (
  `recipes_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `resources_quantity` DECIMAL NULL,
  `recipes_resourcescol` VARCHAR(45) NULL,
  PRIMARY KEY (`recipes_id`, `resources_id`),
  INDEX `fk_recipes_has_resources_resources1_idx` (`resources_id` ASC) VISIBLE,
  INDEX `fk_recipes_has_resources_recipes1_idx` (`recipes_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipes_has_resources_recipes1`
    FOREIGN KEY (`recipes_id`)
    REFERENCES `mydb`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_has_resources_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`market`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`market` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resources_id` INT NOT NULL,
  `users_seller_id` INT NOT NULL,
  `users_buyer_id` INT NOT NULL,
  `price_unit` DECIMAL NULL,
  `quantity` FLOAT NULL,
  `sold_at` DATETIME NULL,
  `bought_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_market_resources1_idx` (`resources_id` ASC) VISIBLE,
  INDEX `fk_market_users1_idx` (`users_seller_id` ASC) VISIBLE,
  INDEX `fk_market_users2_idx` (`users_buyer_id` ASC) VISIBLE,
  CONSTRAINT `fk_market_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_market_users1`
    FOREIGN KEY (`users_seller_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_market_users2`
    FOREIGN KEY (`users_buyer_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
